baseURL = 'https://pdeguing.github.io/skydivingwithawhale/'
languageCode = 'fr-fr'
title = 'Skydiving with a whale'
theme = 'paper'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

# ------------------------------
theme = "hugo-paper"

[params]
  color = 'linen'         # linen, wheat, gray, light
  monoDarkIcon = true

# ------------------------------