baseURL = 'https://skydivingwithawhale.com/'
title = 'skydiving with a whale'
theme = "paper"
languageCode = 'fr-fr'

# multilingual
defaultContentLanguage = 'fr'
defaultContentLanguageInSubdir = true
[languages]
[languages.fr]
contentDir = 'content/fr'
disabled = false
languageCode = 'fr-fr'
languageDirection = 'ltr'
languageName = 'Français'
weight = 1
[languages.en]
contentDir = 'content/en'
disabled = false
languageCode = 'en-us'
languageDirection = 'ltr'
languageName = 'English'
weight = 2

[params]
#theme options
color = 'linen' # linen, wheat, gray, light

# header social icons
twitter = 'pdeguing' # twitter.com/YOUR_TWITTER_ID
github = 'pdeguing'  # github.com/YOUR_GITHUB_ID

# home page profile
avatar = 'https://www.gravatar.com/avatar/ef333c1203724d1cb48104b2679529bb?s=160&d=identicon' # gravatar email or image url
name = 'PQ'
bio = 'Think.'

# misc
disableHLJS = true                       # disable highlight.js
disablePostNavigation = true             # disable post navigation
monoDarkIcon = true                      # show monochrome dark mode icon
gravatarCdn = 'GRAVATAR_CDN_LINK'        # e.g. 'https://cdn.v2ex.com/gravatar/'
math = true                              # enable KaTeX math typesetting globally
localKatex = false                       # use local KaTeX js/css instead of CDN
graphCommentId = "YOUR_GRAPH_COMMENT_ID" # use graph comment (disqus alternative)
favicon = "favicon.ico"                  # customize the default favicon
appleTouchIcon = "apple-touch-icon.png"  # customize the default Apple touch icon
