baseURL = 'https://pdeguing.github.io/skydivingwithawhale/'
languageCode = 'fr-fr'
title = 'skydiving with a whale'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"